version: '3.3'
services:
    postgres:
        container_name: n2n_postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=admin4321
        ports:
            - '5432:5432'
        volumes:
            - '$HOME/docker/volumes/postgres:/var/lib/postgresql/data'
        image: postgres