version: "3.8"

services:
  es01:
    build: .
    image: elasticsearch-7.12
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /home/elasticsearch/data01
        target: /usr/share/elasticsearch/log
      - type: bind
        source: /home/elasticsearch/logs01
        target: /usr/share/elasticsearch/logs
   
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    build: .
    image: elasticsearch-7.12
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /home/elasticsearch/data02
        target: /usr/share/elasticsearch/data
      - type: bind
        source: /home/elasticsearch/logs02
        target: /usr/share/elasticsearch/logs
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
