# Elasticsearch 7.11.2

# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/elasticsearch/elasticsearch:7.12

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
