version: "3.3"
services:
  PGroonga:
    container_name: n2n_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin4321
    volumes:
      - "$HOME/docker/volumes/postgres:/var/lib/postgresql/data"
    image: groonga/pgroonga:latest
